Refactor components to use new token structure
selsa-inube/inubekit-blanket pull request #2
Opened 2024-03-11 22:41 UTC by JanuarAsprilla

on this card, the `Blanket `component has been refactored to use the new token structure offered by **foundations** as well as the updated dependencies.

2024-03-12 16:43 UTC, cmarin001 requested changes

2024-03-12 16:43 UTC, cmarin001 commented on src/Blanket/index.tsx
> +interface IBlanketProps {
it would be better use just IBlanket instead of IBlanketProps

2024-03-12 21:10 UTC, JanuarAsprilla commented on src/Blanket/index.tsx
> +interface IBlanketProps {
solved

2024-03-13 14:13 UTC, wfercanas approved these changes

2024-03-13 15:50 UTC, merged